export const FETCH_MOVIES = "FETCH_MOVIES";

export const SEARCH_MOVIE = "SEARCH_MOVIE";

export const REMOVE_SEARCH_MOVIES = "REMOVE_SEARCH_MOVIES"

export const MOVIE_DETAILS = "MOVIE_DETAILS"

export const REMOVE_MOVIES = "REMOVE_MOVIES"